### ISSUE TITLE
makeconcat error

### ISSUE THREAD

**Issue by BleakleyMcD** [NMAAHC/nmaahcmm#10]
This is the same error Candace emailed about a bit earlier today.
```
/Users/medialab
≈:≈ makeconcat /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video01.mov /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video02.mov 

 Please enter the name of the concatenated file to be created, for example, SC_0001_20171211_Mangum_R8_01
 Enter file name: 
TEST

/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 55: ffmpeg: command not found

/usr/local/bin/makeconcat: line 57: cowsay: command not found

/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 Your concatenated file is: /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/TEST.mov
/usr/local/bin/nmaahcmmfunctions: line 151: date: command not found
/usr/local/bin/nmaahcmmfunctions: line 151: basename: command not found
/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 makeconcat process complete.

/Users/medialab
≈:≈ 
```

Those are all installed on this machine.

**Comment by BleakleyMcD** [comment]
```
/Users/medialab
≈:≈ makeconcat /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video01.mov /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video02.mov 

 Please enter the name of the concatenated file to be created, for example, SC_0001_20171211_Mangum_R8_01
 Enter file name: 
TEST

/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 55: ffmpeg: command not found

/usr/local/bin/makeconcat: line 57: cowsay: command not found

/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 Your concatenated file is: /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/TEST.mov
/usr/local/bin/nmaahcmmfunctions: line 151: date: command not found
/usr/local/bin/nmaahcmmfunctions: line 151: basename: command not found
/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 makeconcat process complete.

/Users/medialab
≈:≈ echo $PATH
~/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin

/Users/medialab
≈:≈ which ffmpeg
/usr/local/bin/ffmpeg

/Users/medialab
≈:≈ which touch
/usr/bin/touch

/Users/medialab
≈:≈ touch TEXT.txt

/Users/medialab
≈:≈ 
```

Hmmm

**Comment by aeschweik** [comment]
Hi Blake,

This is definitely weird and we were working on it with Candace. I asked her to run `echo $PATH` on the medialab computer and this was the result:

```
/Users/medialab
≈:≈ echo $PATH
/usr/local/opt/e2fsprogs/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin
```

This is of course not the same $PATH as in NMAAHC's bashrc, which should be:
`export PATH="~/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin"`

I'm not 100% on why it has stopped exporting properly but I have a few troubleshooting ideas.


1. Edit main ~/.bashrc file:
Open ~/.bashrc in a text editor and check for an `export PATH=` statement. Does it look like the NMAAHC bashrc? If not, I would first try to source the NMAAHCmm bashrc, by adding the following to the ~/.bashrc file:
```
if [ -f /PATH/TO/NMAAHCBASHRC ]; then
   source /PATH/TO/NMAAHCBASHRC
fi
```
If that doesn't work, I would at least overwrite the export PATH= line with the NMAAHC bashrc $PATH.
Save and close the file, then back in the terminal, type "source ~/.bashrc". (This should reload the bashrc file.)


2. Edit ~/.bash_profile:
Sometimes your ~/.bash_profile gets read by the shell before your ~/.bashrc file. In order to make the shell read the ~/.bashrc file, open ~/.bash_profile in a text editor and add the following code:
```
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```
Here's a link with more info about the difference between the two: http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html


3. The Homebrew FAQ route:
If this all fails, run the following in the terminal, and then reboot the computer (as per the Homebrew FAQ) - this will reset the path for all users on the computer:
sudo launchctl config user path "/usr/local/bin:$PATH"


Let me know if these fixes work, and if you see anything unexpected in the bashrc or bash_profile files. (And sorry for neglecting, I mixed up this email with Candace's!)

**Comment by BleakleyMcD** [comment]
Hi Annie,

I had the same problems on another workstation when the PATH read

`
/Users/medialab
≈:≈ echo $PATH
~/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin`

Our .bashrc file for all workstations is in our nmaahcmm repo I may move it to its own repo. 

.bash_profile reads:


`if [ -f ~/.bashrc ]; then
source ~/.bashrc
fi

ln -s /usr/local/bin/bashrc ~/.bashrc`

I sourced the .bashrc file before running `echo $PATH`

currently away from the office but the issue still seems valid since the $PATH was correct.

**Comment by aeschweik** [comment]
Does the problem persist on that computer if you set the $PATH so that /usr/local/bin comes before ~/bin ?

**Comment by NMAAHC** [comment]
```
/Users/medialab
≈:≈ makeconcat /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video01.mov /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video02.mov 

 Please enter the name of the concatenated file to be created, for example, SC_0001_20171211_Mangum_R8_01
 Enter file name: 
TEST

/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 55: ffmpeg: command not found

/usr/local/bin/makeconcat: line 57: cowsay: command not found

/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 Your concatenated file is: /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/TEST.mov
/usr/local/bin/nmaahcmmfunctions: line 151: date: command not found
/usr/local/bin/nmaahcmmfunctions: line 151: basename: command not found
/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 makeconcat process complete.

/Users/medialab
≈:≈ echo $PATH
~/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin

/Users/medialab
≈:≈ source .bashrc
Hello NMAAHC Media Conservation!
Be All That You Can Be Today!
Let's Go!

/Users/medialab
≈:≈ echo $PATH
/usr/local/bin:~/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin

/Users/medialab
≈:≈ makeconcat /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video01.mov /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/OH_Video02.mov 

 Please enter the name of the concatenated file to be created, for example, SC_0001_20171211_Mangum_R8_01
 Enter file name: 
TEST

/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 49: touch: command not found
/usr/local/bin/makeconcat: line 55: ffmpeg: command not found

/usr/local/bin/makeconcat: line 57: cowsay: command not found

/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 Your concatenated file is: /Volumes/SI_11653/PearlBowserFilmCollectionOralHistoryVideos/TEST.mov
/usr/local/bin/nmaahcmmfunctions: line 151: date: command not found
/usr/local/bin/nmaahcmmfunctions: line 151: basename: command not found
/usr/local/bin/nmaahcmmfunctions: line 203: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 204: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 205: tput: command not found
/usr/local/bin/nmaahcmmfunctions: line 206: tput: command not found
 makeconcat process complete.

/Users/medialab
≈:≈ 
```

Yes, it appears so.

**Comment by aeschweik** [comment]
I looked through the script updates again and found that I changed the variable "$path" in makeconcat to be all upper-case - I think that may be the source of the issue. (If it is, I am really sorry!)

I opened a PR #11 that should address it, or you can make the change on your end (see commit 49d293c, note it also changes another important variable from uppercase to lowercase - "FILE" to correct "file" in the ffmpeg concat command).

Hope that works but if it doesn't, try:
`hash -r`
to clear the cache in case the wrong path got stored by the shell.
(man page: https://ss64.com/bash/hash.html)

**Comment by lawrenceaj** [comment]
Hi Annie,
I updated the script and now I'm getting this error:
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
  2020-02-11T14:33:33 - /usr/local/bin/makeconcat: Can't create log directory at ./Desktop/logs, exiting...
mkdir: ./Desktop: No such file or directory
Segmentation fault: 11

**Comment by NMAAHC** [comment]
I just merged the PR and makeconcat now works again. Thanks!

For other terminals `brewUp` and maybe `brew install nmaahcmm --HEAD`
