### ISSUE TITLE
mkvnote Error: (mkvextract) This file could not be opened or parsed.

### ISSUE THREAD

**Issue by chialinchou1** [NMAAHC/nmaahcmm#106]
Related to #105 @dericed 

Running same file on a machine with swift dialog newly installed. It calls up the GUI:
<img width="923" alt="Screenshot 2024-10-11 at 3 56 06 PM" src="https://github.com/user-attachments/assets/0e1166ee-891f-4071-a8c8-052eb16e5f7b">
But shows error on terminal screen `Error: (mkvextract) This file could not be opened or parsed.`

Type in text in fields and will show in terminal screen but with error message: `Error: The file '/Volumes/JPCARCHIVE/00_fromDMZ/01_mkvEmbed_Testing/JPC_AV_01567.mkv' is not a Matroska file or it could not
be found.`
<img width="925" alt="Screenshot 2024-10-11 at 3 57 19 PM" src="https://github.com/user-attachments/assets/37ebbde0-6508-4116-a39d-ef8a04aeed9d">

Ran `mediainfo `for the mkv file with no response.

cc. @BleakleyMcD @EmCNabs

**Comment by BleakleyMcD** [comment]
no longer using swift dialog. closing.
