### ISSUE TITLE
LTOpers errors

### ISSUE THREAD

**Issue by lawrenceaj** [NMAAHC/nmaahcmm#12]
Hi-

I installed https://raw.githubusercontent.com/piste2750/homebrew-ltfs/master/ltfs.rb, but there was no improvement. I'm still getting an unsupported drive error, which is what happened with our other attempts at using alternative's to Quantum. Perhaps our Quantum drives only work with Quantum's LTFS variation? 

Perhaps it's time to bring in the Mac Pro tower we previously used for writing LTO?

**Comment by dericed** [comment]
Hi @lawrenceaj, I think this is fixed by installed ltfs with --enable-buggy-ifs. I added an issue at https://github.com/piste2750/homebrew-ltfs/issues/2.

**Comment by dericed** [comment]
closed with https://github.com/piste2750/homebrew-ltfs/issues/2
