### ISSUE TITLE
makeh264 placing files in "metadata" directory

### ISSUE THREAD

**Issue by BleakleyMcD** [NMAAHC/nmaahcmm#19]
I can fix this but trying to remember if we were thinking "metadata" over, say, "derivative" for a specific reason. "derivative" or "access" or something seems more appropriate than "metadata" @aeschweik

**Comment by aeschweik** [comment]
No reason it has to be "metadata"! That's a holdover from the CUNY mediamicroservices language ([ingestfile](https://github.com/mediamicroservices/mm/blob/master/ingestfile) makes "objects" and "metadata" packages). The directory can be called whatever makes the most sense at NMAAHC.

**Comment by dericed** [comment]
Fixed by https://github.com/NMAAHC/nmaahcmm/commit/4db38b096162481dc357a2bf3b01774d9ba1bf65
