### ISSUE TITLE
makeGM only works on ScanSan

### ISSUE THREAD

**Issue by NMAAHC** [NMAAHC/nmaahcmm#21]
testing makeGM outside of NMAAHC's TBMA server (ScanSan) doesn't work. Can mkdir be changed to run on any directory or a directory of the user's choosing?

**Comment by NMAAHC** [comment]
mkdir: /Volumes/ScanSAN/00_Great_Migration_SC_0001/2018/03_March_2018/20210507_TEST_TSET: Permission denied
touch: /Volumes/ScanSAN/00_Great_Migration_SC_0001/2018/03_March_2018/20210507_TEST_TSET/20210507_TEST_TSET_generalNotes.txt: No such file or directory
/usr/local/bin/makeGM: line 33: /Volumes/ScanSAN/00_Great_Migration_SC_0001/2018/03_March_2018/20210507_TEST_TSET/20210507_TEST_TSET_generalNotes.txt: No such file or directory
mkdir: /Volumes/ScanSAN/00_Great_Migration_SC_0001/2018/03_March_2018/20210507_TEST_TSET/16mm/ACCESS: Permission denied
mkdir: /Volumes/ScanSAN/00_Great_Migration_SC_0001/2018/03_March_2018/20210507_TEST_TSET/16mm/PRESERVATION: Permission denied
/usr/local/bin/makeGM: line 47: 16MM_NOTES=/Volumes/ScanSAN/00_Great_Migration_SC_0001/2018/03_March_2018/20210507_TEST_TSET/16mm/20210507_TEST_TSET_16mm_Notes.txt: No such file or directory
/usr/local/bin/makeGM: line 48: ${16MM_NOTES}: bad substitution
MingC@NMAAHC-L37332 ~ % gmconfig

/Volumes/ScanSAN is not found. This location must be present for script to run. Exiting.

**Comment by BleakleyMcD** [comment]
try running `gmconfig` in terminal first. That should pull up a Pashua window where you can choose the path for the directory to save to.

**Comment by NMAAHC** [comment]
I was able to get gmconfig window up and running but I'm now getting this error when I try to save: "/usr/local/bin/gmconfig: line 310: /usr/local/bin/gm.conf: Permission denied"

**Comment by NMAAHC** [comment]
Hi Dave,
Unfortunately that isn't working. I'm using "sudo gmconfig" to make changes and one thing I just noticed is that if only 1 format is selected, the ACCESS and PRESERVATION files don't populate.

**Comment by dericed** [comment]
Hi @NMAAHC, can you send us an output of `ls -l /usr/local/bin/gm.conf`.

**Comment by aeschweik** [comment]
Hi CK, thanks for reporting. I made some further updates that should help debug in PR #22. Would you mind updating to the latest version and letting us know if the issue persists?

**Comment by BleakleyMcD** [comment]
> `sudo chown $USER /usr/local/bin/gm.conf`

chown: /usr/local/bin/gm.conf: No such file or directory

**Comment by BleakleyMcD** [comment]
gmconfig exits with `bleakley@NMAAHC-L34970H ~ % gmconfig
/opt/homebrew/bin/gmconfig: line 310: /opt/homebrew/bin/gm.conf: Permission denied`

**Comment by BleakleyMcD** [comment]
running `chmod 777 /opt/homebrew/bin/gm.conf` and  `chmod 777 /opt/homebrew/bin/gmconfig` made it work.

**Comment by BleakleyMcD** [comment]
done
