### ISSUE TITLE
Add installation instructions to README

### ISSUE THREAD

**Issue by mingosthename** [NMAAHC/nmaahcmm#32]
Can we add the installation instructions via homebrew for the scripts? I'm having trouble installing the package and I'm not sure what I'm doing wrong. It would be great to have a reference for when we need to install or re-install the microservices.

**Comment by mingosthename** [comment]
hit the wrong button!

**Comment by mingosthename** [comment]
trying again

**Comment by chialinchou1** [comment]
Hi CK @mingosthename,

Thanks for bringing up this. You don't need to brew install these scripts/package. You can just git clone the repo to your local machine (make sure you create a designate directory for it), here's the quick steps:
1.  In Terminal, make sure you are in the directory you want to save the mmservices.   Type in command:                
        git clone https://github.com/NMAAHC/nmaahcmm
2. In Finder, go to nmaahcmm folder.
3. Double click nmaahcmmconfig 
(If nmaahcmmconfig can’t install pashua automatically, go to terminal and type in command:  brew install pashua)
4. In Finder, double click the mmservices you want to use, or in Terminal, in the directory of the mmservices, type in 
./[mmservices name], for example: ./camera_cards

Hope this helps! I'm working with @BleakleyMcD to make documentations, so will make sure add the instructions! 

Chialin

**Comment by mingosthename** [comment]
Hi Chialin,
Thanks for this! Do I have to input directories for the nmaahcmm config? It would be great to be able to choose these paths as we create them since it can change.

**Comment by mingosthename** [comment]
OK I made some arbitrary folders and it seems to be working now!

**Comment by mingosthename** [comment]
However, it doesn't work outside of that nmaahcmm folder--I thought we were able to do that on our previous computer, i.e. run the microservices from any directory. Is there a step I'm missing to do that
<img width="432" alt="Screen Shot 2022-03-17 at 16 33 04EDT" src="https://user-images.githubusercontent.com/92872258/158890349-ebef4eed-1715-41ba-9408-a6fde3bb6e2e.png">
.

**Comment by BleakleyMcD** [comment]
The ‘dot’ referers to the directory you are in, which looks to be the
desktop. So if you have the script directly on the desktop it will run. But
that probably not where it is and rally shouldn’t be.

Change directory (cd) to the directory containing the script (it should be
in something like ‘medialab/github/nmaahc/nmaahcmm’ and then you could run
it with ‘./makeh264’

**Comment by mingosthename** [comment]
Hey Blake, 
Yes I was successful in running it from the nmaahcmm directory, but I thought on the trashcan we didn't have to be in the nmaahcmm directory to run the scripts. Maybe I'm not remembering correctly.

**Comment by BleakleyMcD** [comment]
Oh we didn’t on the trash can because it was installed differently via
homebrew. We can set it up that way again but it also works well this way
and is a bit more straightforward. This was kinda the Lorena was teaching
at the workshop

**Comment by EmCNabs** [comment]
Hi All,

I am able to run functions without being in the nmaahcmm directory.  Though this may be because I also installed CUNY's mediamicroservices/mm when I was trying to figure out how to configure NMAAHC micromediaservices

**Comment by BleakleyMcD** [comment]
There have been updates in the past few months, so yes it should work as it was originally working again via homebrew. 

Make sure you have version 0.4 installed. 

Thanks!
