### ISSUE TITLE
Errno::ENOENT: No such file or directory - camera_cards

### ISSUE THREAD

**Issue by BleakleyMcD** [NMAAHC/nmaahcmm#34]
/Users/bleakley
(base) ≈:≈ brew install nmaahcmm
==> Downloading https://github.com/NMAAHC/nmaahcmm/archive/v0.0.3.1.tar.gz
Already downloaded: /Users/bleakley/Library/Caches/Homebrew/downloads/564c2b462e6430c9f0585aeeece46f5be96ddeae79d904b948d1858aeffe15c8--nmaahcmm-0.0.3.1.tar.gz
==> Installing nmaahcmm from nmaahc/nmaahcmm
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - camera_cards

**Comment by BleakleyMcD** [comment]
@aeschweik

**Comment by aeschweik** [comment]
Hi Blake, would you mind running `brew install nmaahcmm --debug` and letting me know the output? Thanks!

**Comment by BleakleyMcD** [comment]
resolved. @aeschweik
