### ISSUE TITLE
makeframemd5 

### ISSUE THREAD

**Issue by EmCNabs** [NMAAHC/nmaahcmm#44]
I saw an Issue Fix for this was pulled & mergerd to NMAAHCMM, but this function is still not working for me.

![Screen Shot 2022-06-02 at 2 15 28 PM](https://user-images.githubusercontent.com/91743959/171702158-56bb1105-ce1e-4da3-9d7b-7557d045e48e.png)

**Comment by EmCNabs** [comment]
Thanks Dave!

**Comment by BleakleyMcD** [comment]
merged!

**Comment by dericed** [comment]
Thanks. @EmCNabs lemme know
