### ISSUE TITLE
makemetadata error

### ISSUE THREAD

**Issue by EmCNabs** [NMAAHC/nmaahcmm#45]
Similar issue as with the "makeframemd5" function. When I try to run the "makemetadata" function it comes back with an error saying it is dependent on "mkvpropedit" but that cannot be installed.

![makemetadata_error](https://user-images.githubusercontent.com/91743959/171714219-64539d42-cab4-41da-b42e-2bc3c297f100.png)

**Comment by kieranjol** [comment]
That is a tool within the mkvtoolnix package, so you can try
brew install movtoolnix
Which should hopefully resolve the issue.

K

**Comment by kieranjol** [comment]
That is a tool within the mkvtoolnix package, so you can try
brew install mkvtoolnix
Which should hopefully resolve the issue.
