### ISSUE TITLE
Camera Cards: Additional options

### ISSUE THREAD

**Issue by chialinchou1** [NMAAHC/nmaahcmm#49]
Hi @aeschweik,

Option C works beautifully! Thank you!! Two minor things: 
1. The checksum for the concatenated media file is still taking the entire filepath, is there a way to only print the file name?
For example now: 
<img width="629" alt="Screen Shot 2022-07-11 at 3 37 05 PM" src="https://user-images.githubusercontent.com/91981823/178344506-7072d02b-a43b-41fc-846c-844a99535328.png">
change to:
<img width="400" alt="Screen Shot 2022-07-11 at 3 35 38 PM" src="https://user-images.githubusercontent.com/91981823/178344302-e9296a3c-2978-4234-9239-55cb290fffcb.png">
2. In the help text for  `-c` there's mention of  `or you can supply both` : I tried to drop the top folder (with both cards under) but unless I supply a second input directory, it quits with error. 

It seems like the current option assumes only two cards (which might be the majority of the cases) I'm wondering if it is possible to add a prompt to input the total card numbers before adding the cards, so that the times for user to add cards would depend on the total number of cards?

Additionally, I wanted to check in about the option to wrap the concatenated file in mkv (for embedded metadata?), as well as adding an option for different types of report (ex. -rm for mediainfo, -rf for ffprobe, -re for exiftool, and nothing for all as it is now?)

Thank you again for your amazing work!! 
Chialin

cc. @BleakleyMcD @dericed

**Comment by BleakleyMcD** [comment]
@dericed @chialinchou1 can this issue be closed?

**Comment by chialinchou1** [comment]
Yes. Most of this has been resolved, or combined with other issues
