### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by NMAAHC** [NMAAHC/nmaahcmm#6]
No file was actually created; script exited instantly.

≈:≈ makeh264 /Users/medialab/RFS_Chicago/01_CommunityCuration/Adobe\ Premiere\ Pro\ Captured\ Video/July4th2001/SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001.mov 
usage: dirname path
mkdir: /derivative: Permission denied
mediaid is: SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001
The output directory is: /derivative
output is: /derivative/SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001.mp4

making .mp4 derivative of SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/medialab/RFS_Chicago/01_CommunityCuration/Adobe Premiere Pro Captured Video/July4th2001/SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2019-09-24T17:20:07.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iMacPro1,1
    com.apple.quicktime.software: Mac OS X 10.14.5 (18F132)
    com.apple.quicktime.creationdate: 2019-09-24T12:20:03-0500
  Duration: 00:54:47.55, start: 0.000000, bitrate: 30510 kb/s
    Stream #0:0(und): Audio: pcm_s16le (lpcm / 0x6D63706C), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2019-09-24T17:20:07.000000Z
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: dvvideo (dvc  / 0x20637664), yuv411p(smpte170m/smpte170m/bt709, bottom coded first (swapped)), 720x480 [SAR 8:9 DAR 4:3], 28771 kb/s, SAR 10:11 DAR 15:11, 29.97 fps, 29.97 tbr, 30k tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2019-09-24T17:20:07.000000Z
      handler_name    : Core Media Video
      encoder         : DV/DVCPRO - NTSC
      timecode        : 00:00:05;06
    Stream #0:2(und): Data: none (tmcd / 0x64636D74), 0 kb/s
    Metadata:
      creation_time   : 2019-09-24T17:20:07.000000Z
      handler_name    : Core Media Time Code
      reel_name       : SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001
      timecode        : 00:00:05;06
/derivative/SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001.mp4: No such file or directory

Success! Derivative SC0001_20190924_GreenwellAva_MiniDV_01_July4th2001.mp4 created.

Moving to next file if present...
makeH264 process complete.

**Comment by NMAAHC** [comment]
@aeschweik

**Comment by aeschweik** [comment]
I am guessing that the problem comes from this line:

`mkdir: /derivative: Permission denied`

This seems to imply that you do not have permission to write to the parent directory `/Users/medialab/RFS_Chicago/01_CommunityCuration/Adobe\ Premiere\ Pro\ Captured\ Video/July4th2001/`. Try running `chmod 775` on the parent directory, then retrying the command, and let me know what happens.

**Comment by aeschweik** [comment]
This is also a good reminder that the script should check to see if the derivative has actually been created before announcing "Success"! So I'll change that. 😅

**Comment by kieranjol** [comment]
I've been guilty of misleadingly success prompts a lot 🙈

**Comment by aeschweik** [comment]
(corrected "success" feedback in commit https://github.com/aeschweik/nmaahcmm/commit/92476a6bc5614d1ba85db5387dd0e452de4087ee)

**Comment by NMAAHC** [comment]
Thanks! fixed.
