### ISSUE TITLE
makeconcat also not working

### ISSUE THREAD

**Issue by NMAAHC** [NMAAHC/nmaahcmm#7]
No file created; script exited instantly.

/Users/medialab
≈:≈ makeconcat /Users/medialab/RFS_Chicago/01_CommunityCuration/Adobe\ Premiere\ Pro\ Captured\ Video/SUmmer2003/SC0001_20190924_GreenwellAva_DVCam_01_Summer2003_a\ 00.mov /Users/medialab/RFS_Chicago/01_CommunityCuration/Adobe\ Premiere\ Pro\ Captured\ Video/SUmmer2003/SC0001_20190924_GreenwellAva_DVCam_01_Summer2003_a\ 01.mov /Users/medialab/RFS_Chicago/01_CommunityCuration/Adobe\ Premiere\ Pro\ Captured\ Video/SUmmer2003/SC0001_20190924_GreenwellAva_DVCam_01_Summer2003_a\ 02.mov 

Please enter the name of the concatenated file to be created.
	 For example, SC_0001_20171211_Mangum_R8_01
Enter file name: C0001_20190924_GreenwellAva_DVCam_01_Summer2003

touch: Premiere/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
/usr/local/bin/makeconcat: line 47: Premiere/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
touch: Pro/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
/usr/local/bin/makeconcat: line 47: Pro/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
touch: Captured/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
/usr/local/bin/makeconcat: line 47: Captured/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
touch: Video/SUmmer2003/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
/usr/local/bin/makeconcat: line 47: Video/SUmmer2003/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
touch: 00.mov/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
/usr/local/bin/makeconcat: line 47: 00.mov/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory
ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.4_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
00.mov/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.txt: No such file or directory

 _______________________________________ 
/ Done. Your concatenated video file is \
\ ready fo action.                      /
 --------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

Your concatenated file is: 00.mov/C0001_20190924_GreenwellAva_DVCam_01_Summer2003.mov\nmakeconcat process complete.

@aeschweik

**Comment by aeschweik** [comment]
It looks like the script is having trouble with the spaces in the filenames - you can see it loops over the words "Adobe Premiere Pro Captured Video" as if they're separate arguments. The most effective way to fix this would be to rename that directory without spaces, and also to remove the spaces in the filenames themselves - e.g. "SC0001_20190924_GreenwellAva_DVCam_01_Summer2003_a_02.mov" instead of 
"SC0001_20190924_GreenwellAva_DVCam_01_Summer2003_a 02.mov"

Would that work for you? In the meantime I can work on ways to preserve whitespaces in the file path, but I'll need to make sure that the command line input can distinguish between whitespaces in one argument vs. whitespaces as delimiters between multiple arguments.

The other option is theoretically to wrap the paths in quotes and remove the backslashes. But my machine continues splitting on the whitespaces when I do that, and I'm not yet clear on why!

**Comment by NMAAHC** [comment]
ah ok. we can fix that. thanks!
