### ISSUE TITLE
makegm error

### ISSUE THREAD

**Issue by NMAAHC** [NMAAHC/nmaahcmm#9]
makegm and gmconfig not populating. See below for error log:

/Users/medialab
≈:≈ gmconfig
objc[57405]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb2648cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x114f31cd8). One of the two will be used. Which one is undefined.
/usr/local/bin/gmconfig: line 364: syntax error near unexpected token `fi'
/usr/local/bin/gmconfig: line 364: `fi'

/Users/medialab
≈:≈ makegm
/usr/local/bin/makegm: line 47: 16MM_NOTES=/Volumes/ScanSAN/00_Great_Migration_SC_0001/2018/03_March_2018/20200128_TEST_TSET/16mm/20200128_TEST_TSET_16mm_Notes.txt: No such file or directory
/usr/local/bin/makegm: line 48: ${16MM_NOTES}: bad substitution

**Comment by NMAAHC** [comment]
```
/Users/medialab
≈:≈ gmconfig
objc[30232]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa40e1cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1147b6cd8). One of the two will be used. Which one is undefined.
/usr/local/bin/gmconfig: line 313: /usr/local/bin/gm.conf: Permission denied

/Users/medialab
≈:≈ 
```
 @aeschweik we have another repository for nmaahcgm - should I put issues there or here?

**Comment by aeschweik** [comment]
Hey! Either works - what's your preference? I did add makegm and gmconfig to this repository because they call on so many of the same structures, but I can separate them back out if you prefer.

As for the reported issues from January, let me know if they persist after incorporating updates through PR #14 .

**Comment by BleakleyMcD** [comment]
Ok. I’m fine keeping it in nmaahcmm. I still have the issue above after incorporating PR #14.

**Comment by BleakleyMcD** [comment]
```
/Users/medialab/github/bleakleymcdowell/nmaahcmm
≈:≈ gmconfig
objc[71338]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffac044cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1134d5cd8). One of the two will be used. Which one is undefined.
/usr/local/bin/gmconfig: line 313: /usr/local/bin/gm.conf: Permission denied

/Users/medialab/github/bleakleymcdowell/nmaahcmm
```
still have this error

**Comment by aeschweik** [comment]
When you run `ls -la /usr/local/bin/gm.conf`, what's the output?

I also get the `Class FIFinderSyncExtensionHost is implemented`... problem, usually when I run Pashua, which I believe is an Apple issue - it seems benign as it hasn't caused me issues (though it is alarming output).

**Comment by NMAAHC** [comment]
```
/Users/medialab
≈:≈ ls -la /usr/local/bin/gm.conf 
lrwxr-xr-x  1 medialab  admin  43 Mar  9 18:55 /usr/local/bin/gm.conf -> ../Cellar/nmaahcmm/HEAD-51f9da7/bin/gm.conf

**Comment by aeschweik** [comment]
The permissions look right to me. I wonder if it's confused about the location of gm.conf being set twice (in nmaahcmmfunctions as well as in gmconfig) - it could also be a syntax problem with the if/then statement that ends in line 313. I made fixes for both in PR #15 , try them out and let me know if they don't work?

**Comment by aeschweik** [comment]
Does this issue persist with PR #15 and the recent changes?

**Comment by BleakleyMcD** [comment]
resolved.
